services:
  - type: web
    name: meu-projeto-django
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn meu_projeto.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
